### ISSUE TITLE
Crash on opening FAIRY FORE - Vivid (Hitoshirenu Shourai)

### ISSUE THREAD

**Issue by oSumAtrIX** [abraker95/ultimate_osu_analyzer#31]
I only got osu original tutorial working 

```
C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master>py "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\run.py"
get_time_range
Traceback (most recent call last):
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\run.py", line 232, in request_open_beatmap
    self.open_beatmap(beatmap_filepath)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\run.py", line 237, in open_beatmap
    self.apply_beatmap(beatmap)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\run.py", line 248, in apply_beatmap
    self.map_manager.add_map(beatmap, beatmap.metadata.name)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\gui\widgets\map_manager.py", line 46, in add_map
    if self.currentIndex() == idx: self.map_changed_event(idx)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\misc\callback.py", line 13, in Func
    return func(*args, **kwargs)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\gui\widgets\map_manager.py", line 85, in map_changed_event
    self.map_changed_event.emit(self.tabData(idx))
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\misc\callback.py", line 42, in exec_callbacks
    Func.returns[callback] = callback(*args, **kwargs)
  File "C:\Users\oSumAtrIX\Desktop\ultimate_osu_analyzer-master\run.py", line 356, in change_map
    min_time, max_time = beatmap.get_time_range()
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by abraker95** [comment]
Sorry this took so long. Should be fixed now!
