### ISSUE TITLE
Cannot load replay

### ISSUE THREAD

**Issue by sunny-lan** [abraker95/ultimate_osu_analyzer#36]
When trying to load any replay included in 'unit tests' folder, I get this stack trace
```
Traceback (most recent call last):
  File "run.py", line 472, in dropEvent
    if file_type == 'osr': self.open_replay(path)
  File "run.py", line 295, in open_replay
    replay = ReplayIO.open_replay(replay_filepath)
  File "C:\Users\sunny\Programs\ultimate_osu_analyzer-master\osu\local\replay\replayIO.py", line 17, in open_replay
    replay = Replay(replay_data.read())
  File "C:\Users\sunny\Programs\ultimate_osu_analyzer-master\osu\local\replay\replay.py", line 19, in __init__
    osrparse.replay.Replay.__init__(self, replay_data)
TypeError: __init__() missing 2 required positional arguments: 'pure_lzma' and 'decompressed_lzma'
```
Any hints?
I'll give a try looking into it myself when I have time.

**Comment by sunny-lan** [comment]
Found the issue, osrparse version has breaking changes (4.0.0. 

requirements.txt should have something similar to

```
osrparse=3.0.0
```

**Comment by abraker95** [comment]
Should be fixed now
